### PR TITLE
[14.0][MIG] website_event_snippet_calendar : Migration from v12 to v14

### PR DESCRIPTION
**Pull request by chandni299**
14.0 mig website event snippet calendar

### CODE REVIEW

**Comment by chandni299** [comment]
Hello guys I have been working on this migration PR. I made a small improvement in displaying not only start but end date as well. See the screenshot below how it looks.

calendar_event_list_with_date_end

Do you guys think it is ok to commit this with the migration PR or is it better to create a separate [IMP] PR one for this minor change?

**Review by chienandalu — COMMENTED** [review]
Thanks a lot @chandni299 You should separate pre-commit changes from the migration ones (see guidelines: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch) so it's easier to review. Otherwise there are lots of indentations changes and it's hard to tell if there's a functional change or not. Please do so.

**Comment by chandni299** [comment]
Thanks, @chienandalu for your feedback. I will do so.
For that, Can I close this PR and create a new one as it is easy to separate pre-commit changes from migration ones ?

**Comment by pedrobaeza** [comment]
You can do it in this one with a bit of git-fu, and force pushing the branch, but if it gets complicated, go on with a new PR.

**Comment by chandni299** [comment]
Done. @pedrobaeza @pedrobaeza You can review new [PR#248](https://github.com/OCA/event/pull/248) and close this one if necessary.

**Pull request closed without merging**
