### PR TITLE
[17.0][MIG] website_event_filter_city: Migration to version 17.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
cc @Tecnativa TT51966

@chienandalu @CarlosRoca13 please review

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Cool. Tested and working :+1:

**Comment by pilarvargas-tecnativa** [comment]
The mobile view was missing

image

**Review by chienandalu — APPROVED** [review]
Thanks again :)

**Review by CarlosRoca13 — APPROVED** [review]
Thanks!

**Pull request merged**
