### PR TITLE
[15.0][MIG] website_event_sale_b2x_alt_price: Migration to 15.0

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT41029

please review @CarlosRoca13  @ernesto-garcia-tecnativa

### CODE REVIEW

**Review by ernesto-garcia-tecnativa — APPROVED** [review]
Code / Functional review OK

**Comment by chienandalu** [comment]
re-ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :smile:

**Pull request merged**
