### PR TITLE
[MIG] [16.0] event_project

### PR DESCRIPTION
**Pull request by Shide**
Migration with a lot lot lot of refactors.

- Removed dependency to project_recalculate and removed code that recalculates all the data.
- Simplified a lot project_data_update function and added more fields to propagate.
- Updated README.md accordingly
- Refactored tests to check more fields and add help and rename of functions
- Formatted views and change to xpath instead of direct field xpath.
- Improved task button to show kanban with proper parameters.

MT-1842 @moduon @rafaelbn @EmilioPascual @edlopen @yajo @chienandalu please review if you want :)

### CODE REVIEW

**Review by EmilioPascual — APPROVED** [review]
LGTM. Functional and code reveiw

**Review by edlopen — APPROVED** [review]
LGTM. Code and functional review. Thank you @Shide !

**Review by fcvalgar — APPROVED** [review]
Functional review, 

LGTM thank you @Shide .

https://www.loom.com/share/b1974227c7da4349adf6489c8cec7650)

**Comment by chienandalu** [comment]
Hi @Shide ! I'm afraid we don't maintain this module anymore

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
