### PR TITLE
[10.0][MIG][website_event_filter_selector]

### PR DESCRIPTION
**Pull request by yajo**
Includes update to use new tours api.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Testing on runbot, if I filter by city, the rest of the combos is not updated:

seleccion_003

That only happens with this combo.

**Comment by yajo** [comment]
It should be fixed now, good catch!

**Review by chienandalu — APPROVED** [review]
Functional review :+1:

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Comment by yajo** [comment]
@pedrobaeza merge?

**Comment by pedrobaeza** [comment]
Squash first

**Comment by yajo** [comment]
I squashed old commits a bit also, all of them were mine after all. Migration is now only in 1.

**Pull request merged**
