### PR TITLE
[16.0] [MIG] website_event_contact

### PR DESCRIPTION
**Pull request by Shide**
Done from zero.

https://www.loom.com/share/247932fac049482883ccdf22720e09e9?sid=18eece98-d315-49b4-83eb-90b41ec4d644

MT-7710 @moduon @yajo @rafaelbn @loida-vm please review if you want :)

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Tested in runbot 👍🏼 

/ocabot migration website_event_contact

**Review by Gelojr — APPROVED** [review]
LGTM. Nice job @Shide

**Review by loida-vm — APPROVED** [review]
Functional test successful. 
However I would add to the Readme that this configuration is for the registration page view.
"Go to the website backend  > Register  > And then edit that page"

👍🏼

**Comment by rafaelbn** [comment]
Hello @sbidoul ,

Do you know how can we add (maintainers) the label "hacktoberfest" to the repo we maintain?

Let me know if possible please. Thank you!

Best

**Comment by Shide** [comment]
Hey @sbidoul, could you add "hacktoberfest" label (or topic) to this repo? 
Like this repo https://github.com/OCA/stock-logistics-workflow

https://github.com/topics/hacktoberfest

**Comment by sbidoul** [comment]
I would assume that PSC can add labels to a repo?

If not, maybe open an issue on https://github.com/oca/repo-maintainer-conf to discuss that.

**Pull request merged**
