### PR TITLE
[MIG] website_event_questions_by_ticket: Migration to 13.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration to 13.0

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

image

**Review by fuentes73 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@ioans73 Do you want to keep test commit as is or squash into migration commit ?

**Comment by ioans73** [comment]
@rousseldenis Yes, i keep it if there is no problem

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
