### PR TITLE
[MIG] website_event_type_description: Migration to 10.0

### PR DESCRIPTION
**Pull request by chienandalu**
Event Type Description in Website
=================================

This module extends the functionality of events website to support a custom
description for each event type that will be displayed only when events of that
type are filtered, below the common description for the Events page.

cc @Tecnativa

### CODE REVIEW

**Comment by chienandalu** [comment]
@Yajo How would you better implement this on 10.0 website? Right now it isn't obvious that there is an editable area for the event types...

**Review by pedrobaeza — APPROVED** [review]
Indeed it's not obvious from the user perspective as there are no visual hints, but it works (tried in runbot)! Add a comment in "Known issues" about that, and we can go on.

**Comment by chienandalu** [comment]
Ok. Readme edited and commits squashed.

**Comment by yajo** [comment]
I'd rather go for putting a `<div class="oe_editable oe_empty" t-field="current_category.description"/>` and let users edit it directly through the website editor. Is it possible?

**Comment by pedrobaeza** [comment]
I was able to add the block in the website editor in runbot...

**Review by yajo — APPROVED** [review]
Oops, true; my fault.

**Comment by chienandalu** [comment]
Yes, I was wondering if there is like a sort of placeholder for this cases whenever editing is active.

**Comment by yajo** [comment]
If you add `class="oe_editable oe_empty"` to the div, I think it adds the default placeholder for you.

**Comment by chienandalu** [comment]
I tried with that but the behavior was the same...

**Comment by yajo** [comment]
Then it seems they removed the feature.

**Pull request merged**
