### PR TITLE
[13.0][MIG] website_event_sale_b2x_alt_price: Migration to 13.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT31327

please @sergio-teruel @joao-p-marques review this

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]
Functional review!!

Please add oca_dependencies.txt file with e-commerce repo to avoid to the tests fail

**Comment by CarlosRoca13** [comment]
@sergio-teruel Change done

**Comment by sergio-teruel** [comment]
Thanks @CarlosRoca13

**Review by joao-p-marques — APPROVED** [review]
Code review :+1:

**Pull request merged**
