### PR TITLE
[ADD] event_track_location_overlap: Control track location overlapping

### PR DESCRIPTION
**Pull request by yajo**
New module that allows to forbid overlapping multiple tracks in the same room at the same time... or not.

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This won't work on track creation, as the search won't return yet the new record. You can't put outside the constraint method (`_check_location_overlap`) the check, as you need data in `self` for comparing.

**Comment by yajo** [comment]
But... tests pass, and they do creation to test.

**Comment by pedrobaeza** [comment]
Please try on your local.

**Review by pedrobaeza — APPROVED** [review]

**Comment by rafaelbn** [comment]
Functionally I don't thinks this is correct, check screenshoot:



- In this case I created a event in 2018-04-06
- But the track is in other date which the location is empty and available

**Review by rafaelbn — CHANGES_REQUESTED** [review]
Functionally tested I comment a used case with an error

**Comment by yajo** [comment]
In Odoo, the event start and end dates are manually saved into the `event.event` object, and displayed when calling its `.display_name` field. That's what you are seeing in the exception message (the part you highlighted).

However, nothing forbids a user from saving an event track in a date that falls outside the event dates.

So, possibly that's the problem you are facing. Could you check please? Are you sure both tracks were not overlapping?

Thanks

**Comment by rafaelbn** [comment]
> So, possibly that's the problem you are facing. Could you check please? Are you sure both tracks were not overlapping?

Yes, I'm sure

**Comment by yajo** [comment]
Sorry @rafaelbn I cannot reproduce your failure. I rebuilt the runbot. Could you try again and provide better STR please?

**Comment by pedrobaeza** [comment]
@rafaelbn update your review

**Review by chienandalu — COMMENTED** [review]
The migration to v12 from this is already merged. Shouldn't this one be so?

**Comment by pedrobaeza** [comment]
Yes, let's move on.

**Pull request merged**
