### PR TITLE
[13.0] [MIG] event_registration_cancel_reason: Migration to v13.0

### PR DESCRIPTION
**Pull request by victoralmau**
@Tecnativa TT25334

Please @pedrobaeza, @joao-p-marques  review it

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Thanks @victoralmau :) Tested functionallity :+1: 

Check travis anyway. Mainly linting errors for pre-commit and some files that have execution permissions.

Also, run `oca-gen-addon-readme` if possible to recreate the main `README.rst` file fixing `13.0` version

**Review by joao-p-marques — APPROVED** [review]
Everything seems good! :+1:

**Review by chienandalu — CHANGES_REQUESTED** [review]
The README.rst still has 12.0 version stuff. Check the readme generator tool to fix it: https://github.com/OCA/maintainer-tools#readme-generator

**Comment by pedrobaeza** [comment]
Well, the bot can do it

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
