### PR TITLE
[WIP][FIX] event_email_reminder: Fix tests

### PR DESCRIPTION
**Pull request by pedrobaeza**
Tests are failing in OCA (not in local). Try to see the problem.

I will merge when this gets green.

@Tecnativa

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please @pedrobaeza could you check this? Thanks!

**Comment by pedrobaeza** [comment]
I'm not able to make this green. @Yajo, you should take care of the website_event_filter_selector tests.

**Comment by yajo** [comment]
You should rebase now after #74

**Comment by rafaelbn** [comment]
This PR @pedrobaeza needs a rebase to check

**Comment by pedrobaeza** [comment]
This is already fixed and 9.0 branch is green, so I close.

**Pull request closed without merging**
