### PR TITLE
Migrate script sends cr and version, not env

### PR DESCRIPTION
**Pull request by Martronic-SA**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Not really, openupgradelib passes `env` by default in v10+:

https://github.com/OCA/openupgradelib/blob/926b3dcfaeebe73c0c6e2d29d157760b86889912/openupgradelib/openupgrade.py#L1395

**Comment by Martronic-SA** [comment]
Thank you for your reply. I've had an error on env.cr.
So probably my openupgralib version is not upto date.

**Comment by Martronic-SA** [comment]
the "use_env=True" option is obsolete then?

**Comment by pedrobaeza** [comment]
Yes for 10+

**Pull request closed without merging**
