### PR TITLE
[FIX] vals of event registration

### PR DESCRIPTION
**Pull request by Montxu**
attendee_partner_id is not avaliable in v12.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It's defined in this module... https://github.com/OCA/event/pull/157/files#diff-22bed8d3e426204a537b0d8e18f9f8e3R16

**Comment by Montxu** [comment]
I'm sorry it's my mistake, it's true.
In this way the registration of participants, even if I find the contact in my system and if it is not logged in which partner_id will always be public user, isn't it?

**Comment by pedrobaeza** [comment]
Yes, because Odoo now distinguishes between the partner who does the registration and the attendee itself

**Comment by pedrobaeza** [comment]
Closing as incorrect.

**Comment by Montxu** [comment]
Thanks for explanation and your time.

**Comment by pedrobaeza** [comment]
You are welcome.

**Pull request closed without merging**
