### PR TITLE
Slovene translation added

### PR DESCRIPTION
**Pull request by sysadminmatmoz**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Technically :+1:

**Comment by sysadminmatmoz** [comment]
It's about simple translations, can we speed up the process in any way?

Thanks.

**Comment by pedrobaeza** [comment]
You should properly rebase your branch to be merged. Anyway, another option is to setup Transifex and make the translations there, so the only wait will be until the sync bot passes over that project.

**Comment by sysadminmatmoz** [comment]
I know and I wish it were. I hate making PRs just for translations :smile:

**Comment by sysadminmatmoz** [comment]
Ok, moving everything to https://github.com/OCA/event/pull/9 and closing this one.

**Pull request closed without merging**
