### PR TITLE
[ADD] sale_crm_event_reservation: sell events like a boss

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of *crm_event*, *event_sale_reservation*
and *sale_crm* to support fast generation of event quotations from
opportunities and to allow you to sell events like a boss.

Draft until merged:

- [x] #201
- [x] #203

@Tecnativa TT27664

### CODE REVIEW

**Comment by yajo** [comment]
New features:

imagen
imagen

**Comment by yajo** [comment]
@chienandalu @sergio-teruel The dependencies for this one were merged already, so it can be reviewed. I set runbot to rebuild.

**Comment by chienandalu** [comment]
I think yo must adapt the repo config to avoid this error: https://travis-ci.com/github/OCA/event/jobs/489642517

**Comment by yajo** [comment]
Ready to review.

**Comment by yajo** [comment]
Ping @chienandalu @sergio-teruel! 😅

**Review by sergio-teruel — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
