### PR TITLE
[ADD][13.0] event_type_multicompany

### PR DESCRIPTION
**Pull request by ivantodorovich**
Adds a `company_id` field in `event.type` model and the corresponding security rule

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
Not blocking: would be nice to have a test.
Question: would it be worth to propose this to odoo/master?

**Review by santostelmo — APPROVED** [review]

**Comment by rousseldenis** [comment]
> Question: would it be worth to propose this to odoo/master?

Indeed, would be nice

**Comment by cvinh** [comment]
Hello
Maybe it would be nice in https://www.github.com/oca/multi-company ?
Best regards

**Comment by simahawk** [comment]
> Hello Maybe it would be nice in https://www.github.com/oca/multi-company ? Best regards

this belong to events mainly so I think the current position is ok.

Regarding odoo/master: let's propose for v16 :rofl:

**Pull request merged**
