### PR TITLE
[13.0][MIG] website_event_require_login: Migration to 13.0

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes https://github.com/OCA/event/pull/172

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
Functional review.

@emagdalenaC2i @pedrobaeza @rafaelbn @chienandalu 

Could you have a look?

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Comment by rafaelbn** [comment]
Dear @manuelregidor , thanks for this great contribution!

Do you plan to improve coverage?

"codecov/patch — 66.66% of diff hit (target 90.54%) "

Thanks

**Comment by HaraldPanten** [comment]
Hi @rafaelbn we're not planning to improve codecov at the moment 👍

**Review by rafaelbn — APPROVED** [review]
Functionaly tested in runbot :+1:

**Pull request merged**
