### PR TITLE
[12.0][FIX] website_event_crm: Take into account multiwebsite environments

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT33131

ping @chienandalu @CarlosRoca13

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I think you should do `env["website"].get_current_website()` instead

**Comment by sergio-teruel** [comment]
the get_current_website method returns the website from the domain.
In this case we send a email to a crm lead object in backend with a link to display all events from one category, in this link we need set the correct website and we only can obtain this from crm.lead company website.

**Comment by pedrobaeza** [comment]
I think checking first `website_id` context key, and if not present, putting your code, can be good enough then.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
