### PR TITLE
[13.0][ADD] event_registration_lang

### PR DESCRIPTION
**Pull request by ivantodorovich**
Module that allows to set an attendee language

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't better to go with `partner_event`, and then you have the language there?

**Comment by ivantodorovich** [comment]
`partner_event` is creating a partner for each registration, and it does [some "magic" looking up partners with the same email](https://github.com/OCA/event/blob/8a4cdbc757c269eaf11406f63ae841e03bb7424a/partner_event/models/event_registration.py#L35) that is not always wanted.

In the project I'm working on, the core behaviour + this module is enough

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by chienandalu — COMMENTED** [review]
Code review :+1:

**Pull request merged**
