### PR TITLE
[MIG+FIX] website_event_questions_free_text: integration with website_event_sale

### PR DESCRIPTION
**Pull request by yajo**
This PR supersedes https://github.com/OCA/event/pull/195. It includes all of its commits, rebased, plus an additional one to fix the tests, that were failing as seen in https://github.com/OCA/event/runs/3319805695.

When this module was tested on a database that had `website_event_sale` installed, tests failed:

<details>

```
2021-08-13 07:36:39,651 23030 [1;31m[1;49mERROR[0m openerp_test odoo.addons.website_event_questions_free_text.tests.test_free_text: FAIL: TestFreeText.test_free_text_answer
Traceback (most recent call last):
File "/home/travis/build/OCA/event/website_event_questions_free_text/tests/test_free_text.py", line 39, in test_free_text_answer
self.event_question_free_text,
AssertionError: False != 'Free Text'

2021-08-13 07:36:39,652 23030 [1;32m[1;49mINFO[0m openerp_test odoo.addons.website_event_questions_free_text.tests.test_free_text: Starting TestFreeText.test_free_text_display_name ...
2021-08-13 07:36:39,774 23030 [1;32m[1;49mINFO[0m openerp_test odoo.addons.base.models.res_users: Login successful for db:openerp_test login:demo from 127.0.0.1
2021-08-13 07:36:39,793 23030 [1;32m[1;49mINFO[0m openerp_test odoo.addons.base.models.ir_http: Generating routing map for key 1
2021-08-13 07:36:39,960 23030 [1;33m[1;49mWARNING[0m openerp_test odoo.addons.http_routing.models.ir_http: 400 Bad Request:

Traceback (most recent call last):
File "/home/travis/odoo-13.0/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
result = request.dispatch()
File "/home/travis/odoo-13.0/odoo/http.py", line 809, in dispatch
r = self._call_function(**self.params)
File "/home/travis/odoo-13.0/odoo/http.py", line 350, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/travis/odoo-13.0/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/home/travis/odoo-13.0/odoo/http.py", line 339, in checked_call
result = self.endpoint(*a, **kw)
File "/home/travis/odoo-13.0/odoo/http.py", line 915, in __call__
return self.method(*args, **kw)
File "/home/travis/odoo-13.0/odoo/http.py", line 515, in response_wrap
response = f(*args, **kw)
File "/home/travis/odoo-13.0/addons/website_event_sale/controllers/main.py", line 40, in registration_confirm
cart_values = order.with_context(event_ticket_id=ticket.id, fixed_price=True)._cart_update(product_id=ticket.product_id.id, add_qty=1, registration_data=[registration])
File "/home/travis/odoo-13.0/addons/website_event_sale/models/sale_order.py", line 93, in _cart_update
values.update(super(SaleOrder, self)._cart_update(product_id, line_id, add_qty, set_qty, **kwargs))
File "/home/travis/odoo-13.0/addons/website_sale/models/sale_order.py", line 171, in _cart_update
raise UserError(_("The given product does not exist therefore it cannot be added to cart."))
odoo.exceptions.UserError: ('The given product does not exist therefore it cannot be added to cart.', '')
```

</details>

With this patch, I'm fixing that problem and besides fixing the tests logic. As these tests were using `MockRequest`, there was no need for them to run as an `HttpCase`, and that in fact was raising the integration problem because those requests ran only in `post_install` mode.

So, tests are now more resilient and fast.

@Tecnativa TT31311 closes https://github.com/OCA/event/pull/195

### CODE REVIEW

**Comment by yajo** [comment]
Since this was already approved in https://github.com/OCA/event/pull/195 and it just contains test fixes, merging.

/ocabot merge nobump

**Comment by yajo** [comment]
Bot broken, I'll do an "old school merge"

**Comment by sbidoul** [comment]
The most probable explanation is that the status webhooks were triggered while the bot was restarting, and GitHub retried them a little bit later. So yes, everything operating normally as far as I can tell.

**Comment by yajo** [comment]
Ah ok, then I don't worry anymore, thanks!

**Pull request merged**
