### PR TITLE
[17.0][MIG] event_mail: Migration to 17.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 17.0

Please @sergio-teruel and @chienandalu can you review it?

@Tecnativa TT51530

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Where can I select de template??

image

**Comment by victoralmau** [comment]
The field was shown (before the table) but without label, which caused confusion and made people think it didn't exist. I see that it is something that is like this (confusing) since v13 (or maybe before), I will solve it also in v16 at least.

**Before**
ejemplo

**After**
despues

**Review by chienandalu — APPROVED** [review]
Test and code review :+1:

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
