### PR TITLE
12.0 mig website event require login

### PR DESCRIPTION
**Pull request by Change2improve**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@chienandalu and @pedrobaeza could you review this PR, thanks?

**Review by chienandalu — CHANGES_REQUESTED** [review]
Thanks, @Change2improve Tested on runbot and it works fine

You should regenerate readme parts so the version is bumped

**Comment by emagdalenaC2i** [comment]
@chienandalu I think that the readme is generated automatically.
I tried to install the readme generator of maintainer-tools but it seems that it doesn't work well.
Next week in the code sprint I will try again

**Comment by chienandalu** [comment]
Well, I think that you can edit the README.rst manually anyway (just bump the 11.0 to 12.0)

**Comment by pedrobaeza** [comment]
The README is generated when the PR is merged, but it's true it's ugly now to see `11.0` in the code and can be misleading. Any way, don't worry too much about that.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza and @chienandalu So, Should I edit the readme or could you review and approve this PR?

**Comment by pedrobaeza** [comment]
I have made some squashing and generate the README for you.

**Review by chienandalu — APPROVED** [review]
Thanks again, @Change2improve :+1:

**Pull request merged**
