### PR TITLE
[ADD] website_event_crm: invite customers to website events

### PR DESCRIPTION
**Pull request by yajo**
This module lets you quickly invite customers to existing events on your
website, so they register themselves and remove some administrative
burden from your sales teams.

Depends on:

- [x] #201 

@Tecnativa TT27664

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
You need to rebase so `crm_event` is available as a dependency

**Comment by yajo** [comment]
Thanks, rebased.

**Comment by yajo** [comment]
@sergio-teruel please review

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
