### PR TITLE
[FIX] event_session: conflicting configuration

### PR DESCRIPTION
**Pull request by chienandalu**
- The config is provided by event_mail and the model mismatches the original one.

cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Shouldn't a migration script that removes the ir.default should be provided?

**Comment by chienandalu** [comment]
Well, this shouldn't ever have been here. Is a migration blunder introduced in v11.

**Comment by pedrobaeza** [comment]
OK, let's fast track it

/ocabot merge patch

**Pull request closed without merging**
