### PR TITLE
[FIX][16.0][event_sale_session]Fix bug #353

### PR DESCRIPTION
**Pull request by percevaq**
Issue #353 

Fix integration issue with sales reports.

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
LGTM :+1:  Check pre-commit issues in any case

**Review by ivantodorovich — APPROVED** [review]
LGTM 👌🏻

**Comment by ivantodorovich** [comment]
Could you squash your commits, though? 🙏🏻

**Comment by percevaq** [comment]
I had a local pre-commit problem and that's why I couldn't solve it before uploading it.
I think I have merged it correctly.

**Comment by pedrobaeza** [comment]
I'm afraid not. There are weird changes in a PO file and 2 commits. Please rebase and remove the ugly changes, just putting the real change.

**Comment by percevaq** [comment]
@pedrobaeza, where can I see documentation on how to correctly make the overrun?

Thank you

**Comment by pedrobaeza** [comment]
It's git general knowledge, not something specific of Odoo/OCA. Just search for "git rebase" topics, like https://www.atlassian.com/es/git/tutorials/rewriting-history/git-rebase or https://git-scm.com/book/en/v2/Git-Branching-Rebasing.

**Pull request closed without merging**
