### PR TITLE
[MIG] crm_lead_to_event_registration: Migration to v12

### PR DESCRIPTION
**Pull request by victor-ditay**
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by rafaelbn — COMMENTED** [review]
In the wizard we should filter for upcoming events, not old ones

**Comment by pedrobaeza** [comment]
@rafaelbn you mustn't restrict that selection in any way, as you don't know the intention of that dump.

**Comment by rafaelbn** [comment]
The attendee should be the contact and not the company

**Comment by pedrobaeza** [comment]
That's not something of this module, but maybe `partner_event`.

**Comment by rafaelbn** [comment]
> @rafaelbn you mustn't restrict that selection in any way, as you don't know the intention of that dump.

@pedrobaeza it is an opportunity so the excepted by default is new one. The exception is register to old ones, so if you want to register an exception in an old event you should:

- Search more
- delete filter upcoming
- look for the old event

**Comment by pedrobaeza** [comment]
That's the problem, @rafaelbn, if you restrict here to upcoming, you won't have any way to select them.

**Comment by victor-ditay** [comment]
@rafaelbn Please review

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
