### PR TITLE
[14.0][MIG] event_registration_qr_code: Backport to 14.0

### PR DESCRIPTION
**Pull request by cvinh**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
I'd say the commit tag would be [MIG] as well anyway :)

**Comment by cvinh** [comment]
> I'd say the commit tag would be [MIG] as well anyway :)

Done

**Comment by chienandalu** [comment]
Great :)

**Pull request merged**
