### PR TITLE
[MIG] website_event_excerpt_img: Migration to 10.0

### PR DESCRIPTION
**Pull request by chienandalu**
Excerpt + Image in Events
=========================

This module extends the functionality of website events to support having a
more attractive layout that automatically displays an excerpt of each one, a
"Read more" button, and an image.

It also adds a event priority control in the backend that will display the
event at the top and in a bigger shape in the website.

**Depends on:**

- [x] `html_image_url_extractor` https://github.com/OCA/server-tools/pull/873
- [x] `html_text` https://github.com/OCA/server-tools/pull/874

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase and squash @Yajo's commit a bit.

**Comment by pedrobaeza** [comment]
Why is everything red?

**Comment by chienandalu** [comment]
@pedrobaeza Mmm, I'll rebase again

**Comment by chienandalu** [comment]
@pedrobaeza Well, I'm getting this warning, although these modules were merged long ago:
```
WARNING openerp_template odoo.modules.loading: invalid module names, ignored: html_image_url_extractor, html_text
```

**Comment by yajo** [comment]
Maybe you need `server-tools` in `oca_requirements.txt`?

**Comment by chienandalu** [comment]
@Yajo @pedrobaeza All green now

**Review by pedrobaeza — APPROVED** [review]
@cubells please review

**Review by cubells — COMMENTED** [review]
Captured images are not used anywhere.

You can either add them to the README file or delete them.

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test.

**Pull request merged**
