### PR TITLE
[MIG] website_event_excerpt_img: Migrate to v12

### PR DESCRIPTION
**Pull request by yajo**
- Split readme.
- Sass -> Scss.
- No precompiled CSS.
- Not highlighted events marked with `.bg-light` to improve their aspect.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis and runbot are red

**Review by chienandalu — CHANGES_REQUESTED** [review]
"Images and Description" doesn't show up in the customize options menu

image

**Review by sergio-teruel — APPROVED** [review]
Tested in runbot

**Pull request merged**
